name: pass_vault
description: "My password vault"
publish_to: "none"

version: 1.0.5+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.9.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  local_auth: ^3.0.0
  provider: ^6.1.5+1
  webview_flutter: ^4.13.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.9.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
